[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd web-dashboard && npm ci"]

[phases.build]
cmds = ["cd web-dashboard && npm run build"]

[start]
cmd = "cd web-dashboard && npm start"
